### ISSUE TITLE
OSX make deploy doesn't complete.

### ISSUE THREAD

**Issue by aspaas** [cevap/ion#65]
/usr/bin/python3.4 contrib/macdeploy/custom_dsstore.py "dist/.DS_Store" "Ion-Core"
Traceback (most recent call last):
  File "contrib/macdeploy/custom_dsstore.py", line 44, in <module>
    alias = Alias.from_bytes(icvp['backgroundImageAlias'])
  File "/home/aspa/src/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 319, in from_bytes
    return cls._from_fd(b)
  File "/home/aspa/src/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 305, in _from_fd
    alias.volume.disk_image_alias = Alias.from_bytes(value)
  File "/home/aspa/src/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 319, in from_bytes
    return cls._from_fd(b)
  File "/home/aspa/src/ion/depends/x86_64-apple-darwin11/native/lib/python/dist-packages/mac_alias/alias.py", line 264, in _from_fd
    alias.target.folder_name = value.decode().replace('/',':')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte
make: *** [dist/.DS_Store] Error 1

**Comment by aspaas** [comment]
Before this, I had the following error:

Undefined symbols for architecture x86_64:
  "vtable for MacNotificationHandler", referenced from:
      MacNotificationHandler::instance() in qt_ion_qt-macnotificationhandler.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for MacDockIconHandler", referenced from:
      MacDockIconHandler::MacDockIconHandler() in qt_ion_qt-macdockiconhandler.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "MacDockIconHandler::dockIconClicked()", referenced from:
      dockClickHandler(objc_object*, objc_selector*, ...) in qt_ion_qt-macdockiconhandler.o
ld: symbol(s) not found for architecture x86_64

This appeared to be 2 missing moc_ files.
